let lbImages=[],lbIdx=0;
function openLb(el){const card=el.closest('.card')||el.closest('.cb')?.parentElement;const thumbs=card?.querySelectorAll('.img-thumb')||[];if(!thumbs.length)return;lbImages=Array.from(thumbs).filter(t=>t.style.display!=='none'&&t.complete&&t.naturalWidth>0);if(!lbImages.length)lbImages=Array.from(thumbs).filter(t=>t.style.display!=='none');if(!lbImages.length)return;lbIdx=lbImages.indexOf(el);if(lbIdx<0)lbIdx=0;showLb()}
function showLb(){document.getElementById('lb').classList.add('open');document.body.style.overflow='hidden';updateLb();renderThumbs()}
function closeLb(){document.getElementById('lb').classList.remove('open');document.body.style.overflow=''}
function lbNav(d){lbIdx=(lbIdx+d+lbImages.length)%lbImages.length;updateLb()}
function updateLb(){document.getElementById('lbImg').src=lbImages[lbIdx].src;document.getElementById('lbCt').textContent=(lbIdx+1)+' / '+lbImages.length}
function renderThumbs(){const tc=document.getElementById('lbThumbs');tc.innerHTML='';lbImages.forEach((t,i)=>{const tt=document.createElement('img');tt.className='lb-thumb'+(i===lbIdx?' current':'');tt.src=t.src;tt.onclick=()=>{lbIdx=i;updateLb();renderThumbs()};tc.appendChild(tt)})}
document.addEventListener('keydown',e=>{if(!document.getElementById('lb').classList.contains('open'))return;if(e.key==='Escape')closeLb();if(e.key==='ArrowLeft')lbNav(-1);if(e.key==='ArrowRight')lbNav(1)})
document.getElementById('lb').addEventListener('click',e=>{if(e.target===e.currentTarget)closeLb()})
let touchX=0;document.getElementById('lb').addEventListener('touchstart',e=>{touchX=e.touches[0].clientX});document.getElementById('lb').addEventListener('touchend',e=>{const d=touchX-e.changedTouches[0].clientX;if(Math.abs(d)>50)lbNav(d>0?1:-1)})

function st(tab,btn){document.querySelectorAll('.tc').forEach(t=>t.classList.remove('act'));document.querySelectorAll('.tb').forEach(b=>b.classList.remove('act'));document.getElementById(tab==='hike'?'th':'ta').classList.add('act');btn.classList.add('act');document.getElementById('ft').value=tab;af()}
function af(){const s=(document.getElementById('si').value||'').toLowerCase();const tf=document.getElementById('ft').value;const df=document.getElementById('fd').value;const wf=document.getElementById('fw').value;let v=0,t=0;const at=document.querySelector('.tc.act');at.querySelectorAll('.card').forEach(c=>{t++;const sd=(c.getAttribute('data-search')||'').toLowerCase();const tp=c.getAttribute('data-type')||'';const d=c.getAttribute('data-diff')||'';const dw=parseInt(c.getAttribute('data-drive')||'999');let sh=true;if(tf!=='all'&&tf!==tp)sh=false;if(df!=='all'&&df!==d)sh=false;if(wf!=='all'&&dw>parseInt(wf))sh=false;if(s&&!sd.includes(s)&&!c.textContent.toLowerCase().includes(s))sh=false;if(sh){c.classList.remove('hid');v++}else{c.classList.add('hid')}});document.getElementById('rc').textContent=v===t?`${t} risultati`:`${v} di ${t}`}
function cf(){document.getElementById('si').value='';document.getElementById('ft').value='all';document.getElementById('fd').value='all';document.getElementById('fw').value='all';af()}

(function(){const t=localStorage.getItem('theme');if(t==='light')document.body.classList.add('light');document.getElementById('tb').textContent=document.body.classList.contains('light')?'☀️':'🌙'})();
function toggleTheme(){document.body.classList.toggle('light');const l=document.body.classList.contains('light');localStorage.setItem('theme',l?'light':'dark');document.getElementById('tb').textContent=l?'☀️':'🌙'}
window.addEventListener('scroll',()=>{document.getElementById('btt').classList.toggle('show',window.scrollY>400)})
function getFavs(){try{return JSON.parse(localStorage.getItem('favs')||'[]')}catch{return[]}}
function toggleFav(id,el){const f=getFavs();const i=f.indexOf(id);if(i>-1)f.splice(i,1);else f.push(id);localStorage.setItem('favs',JSON.stringify(f));el.classList.toggle('on',i===-1)}
(function(){const f=getFavs();document.querySelectorAll('.card').forEach(c=>{const h3=c.querySelector('h3');if(!h3)return;const id=h3.textContent.trim().slice(0,40);const btn=document.createElement('button');btn.className='fav-btn'+(f.includes(id)?' on':'');btn.textContent='❤️';btn.title='Preferito';btn.onclick=e=>{e.stopPropagation();toggleFav(id,btn)};const hd=c.querySelector('.ch');if(hd)hd.appendChild(btn);else{const w=c.querySelector('[style*="display:flex"]');if(w)w.appendChild(btn)}})}())
af();
